config/routes.rb
FlashcardApp::Application.routes.draw do

  root :to => 'menus#index'
  resources :flashcards
  resource :deck

end

app/models/deck.rb
class Deck
  def self.build_deck(xml_file)
    card_data = XMLCardParser.retrieve_card_data(xml_file)
    card_data.each do |c|
      exists = Flashcard.find_by_english(c.english)
      if !exists
        Flashcard.create(
          :english => c.english,
          :pinyin => c.pinyin,
          :character => c.character,
          :category => c.category)
      end
    end
  end
end

app/models/flashcard.rb
class Flashcard < ActiveRecord::Base
end

app/models/xml_card_parser.rb
class XMLCardParser
  require 'ostruct'
  require 'open-uri'

  def self.retrieve_card_data(xml_file)
    file = open(xml_file)
    doc = Nokogiri::XML(file)

    all_xml_cards = doc.css("word")
    card_data_for_deck = []

    all_xml_cards.each do |c|
      card_data = OpenStruct.new
      card_data.character = c.css("zh_cn").first.content
      card_data.pinyin = c.css("pinyin").first.content
      card_data.english = c.css("en").first.content
      card_data.category = c.css("tag").first.content
      card_data_for_deck << card_data
    end

    card_data_for_deck
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def show
  end

  def edit
  end

  def update
    xml_file_url = params[:xml_location][:url]
    deck_construction = Deck.build_deck(xml_file_url)
    if deck_construction
      flash.now[:notice] = "Deck built!"
    else
      flash.now[:error] = "Something went wrong. Deck not generated correctly."
    end
    render :action => 'edit'
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def index
    @flashcards = Flashcard.all
  end

  def new
    @flashcard = Flashcard.new
  end

  def create
    @flashcard = Flashcard.new(params[:flashcard])
    @flashcard.save
    flash[:notice] = "Card created"
    redirect_to new_flashcard_path
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/decks/edit.html.erb
<div data-role="page">

  <div data-role="header">
    <div><h1>Provide a URL</h1></div>
  </div>

  <div data-role="content">
    <%= form_for :xml_location, :url => deck_path, :html => {:method => :put} do |f| %>
      <%= f.label :url, "Paste here:" %>
      <%= f.text_field :url %>
      <%= f.submit "Build!" %>
    <% end %>
  </div>

  <div data-role="footer">
    <%= link_to "Back", root_path, :data => {:ajax => "false"} %>
  </div>

</div>

app/views/decks/show.html.erb
<div data-role="page">

  <div data-role="header">
    <div><h1>Build a deck</h1></div>
  </div>

  <div data-role="content">
    <ul data-role="listview">
      <li><%= link_to "Provide a URL", edit_deck_path, :data => {:ajax => "false"} %></li>
    </ul>
  </div>

  <div data-role="footer">
    <%= link_to "Back", root_path, :data => {:ajax => "false"} %>
  </div>

</div>

app/views/flashcards/_flashcard_chinese.html.erb
<%= content_tag(:div, :data => {:role => "page"}, :id => "#{current_card.id}_chinese") do %>
	<div data-role="content">
		<div class="card_contents">
			<div class="card_text">
				<h1><%= current_card.character %></h1>
				<h2><%= current_card.pinyin %></h2>
			</div>
			<div class="card_buttons">
				<p><%= link_to("Flip", "##{current_card.id}_english", :data => {:role => "button", :transition => "flip"})%></p>
				<p><%= link_to("Next", "##{next_card.id}_chinese", :data => {:role => "button", :transition => "slide"})%></p>
			</div>
		</div>
	</div>
	<div data-role="footer">
		<%= link_to "Back", root_path %>
	</div>
<% end %>

app/views/flashcards/_flashcard_english.html.erb
<%= content_tag(:div, :data => {:role => "page"}, :id => "#{current_card.id}_english") do %>
	<div data-role="content">
		<div class="card_contents">
			<div class="card_text">
				<h3><%= current_card.english %></h3>
			</div>
			<div class="card_buttons">
				<%= link_to("Flip", "##{current_card.id}_chinese", :data => {:role => "button", :transition => "flip"})%>
				<%= link_to("Next", "##{next_card.id}_chinese", :data => {:role => "button", :transition => "slide"})%>
			</div>
		</div>
	</div>
<% end %>

app/views/flashcards/index.html.erb
<% if !@flashcards.empty? %>
	<% @flashcards.each_with_index do |current_card, index| %>
		<% @flashcards[index + 1].nil? ? next_card = @flashcards[0] : next_card = @flashcards[index + 1] %>
		<%= render :partial => "flashcard_chinese", :locals => {:current_card => current_card, :next_card => next_card} %>
		<%= render :partial => "flashcard_english", :locals => {:current_card => current_card, :next_card => next_card} %>
	<% end %>
<% else %>
	<div data-role="page">
		<div data-role="content">
			<p>You don't have any cards yet!</p>
		</div>
		<div data-role="footer">
			<%= link_to "Back", root_path %>
		</div>
	</div>
<% end %>

app/views/flashcards/new.html.erb
<div data-role="page">
	<div data-role="header">
		<div><h1>Create a flashcard</h1></div>
	</div>
	<div data-role="content">
		<%= form_for @flashcard do |f| %>
			<%= f.label :english %>
			<%= f.text_field :english %>
			<%= f.label :pinyin %>
			<%= f.text_field :pinyin %>
			<%= f.label :character %>
			<%= f.text_field :character %>
			<%= f.label :category %>
			<%= f.text_field :category %>
			<%= f.submit %>
		<% end %>
	</div>
	<div data-role="footer">
		<%= link_to "Back", root_path, :data => {:ajax => "false"} %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Mo's Flashcard App</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="http://code.jquery.com/mobile/1.1.0-rc.1/jquery.mobile-1.1.0-rc.1.min.css" />
		<script src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
		<script src="http://code.jquery.com/mobile/1.1.0-rc.1/jquery.mobile-1.1.0-rc.1.min.js"></script>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id =>"flash_#{name}", :class => "ui-body ui-body-e" %>
    <% end %>
		<%= yield %>
	</body>
</html>

app/views/menus/index.html.erb
<div data-role="page">

	<div data-role="header">
    <div><h1>Mo's Flashcard App</h1></div>
	</div>

	<div data-role="content">
		<ul data-role="listview" class="ui-listview">
			<li class="ui-btn">
				<%= link_to "View all flashcards", flashcards_path, :data => {:ajax => "false"} %>
			</li>
			<li class="ui-btn">
					<%= link_to "Create a new flashcard", new_flashcard_path, :data => {:ajax => "false"} %>
			</li>
			<li class="ui-btn">
					<%= link_to "Import flashcards", deck_path, :data => {:ajax => "false"} %>
			</li>
		</ul>
	</div>

	<div data-role="footer">
	</div>

</div>